[deps]
BoxCoxTrans = "4c24c29e-1bf7-59e2-a6c7-e500a6482ce4"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ExpectationMaximization = "e1fe09cc-5134-44c2-a941-50f4cd97986a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LRMoE = "b6847444-3cfa-4637-857f-9c8c615f8351"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Lowess = "a2847a04-7795-4581-bff1-964344ea125d"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
QuasiGLM = "e2a73505-cb16-4f72-bfa1-862ae24a0184"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Resample = "318ae45f-2437-4276-8d16-19df99ea8507"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
DrWatson = "2.9.1"
julia = "1.8.5"
